# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ScrollViewMaxHeight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScrollViewMaxHeight
  pod 'SnapKit'
  target 'ScrollViewMaxHeightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrollViewMaxHeightUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
